### ISSUE TITLE
Is ensure_maps useless ?

### ISSUE THREAD

**Issue by gabviv73** [cirrax/puppet-postfixadmin#2]
If include a postfix and dovecot class in my node, and declare in `common.yaml`

    postfixadmin::ensure_maps: true

no sql files are generated.

I had to declare both

    postfixadmin::ensure_postfix_queries: true
    postfixadmin::ensure_dovecot_queries: true

P.S. : what postfix and dovecot puppet modules do you recommend ? It would be nice to have a brief example for a complete stack.

Edit: DUH ! Noticed you have your puppet modules ! I'll take a look ate them.

**Comment by trefzer** [comment]
upps, correct, the documentation is wrong. youre approach is correct. need to adapt the docu in the module.

postfix/dovecot module, correct I use my own modules. But be warned, they allow to configure almost everything and they do not have a verry usefull standart config (since every mailserver is different).
